services:
  agent:
    restart: always
    privileged: true
    pid: host
    image: gcr.io/spiffe-io/spire-agent:0.12.2
    volumes:
      - ${PWD}/conf/agent.conf:/opt/spire/conf/agent/agent.conf
      - ${PWD}/certs/service.pem:/opt/spire/service.pem
      - ${PWD}/certs/service-key.pem:/opt/spire/service-key.pem
      - /tmp/sockets/:/run/spire/sockets/
      - /var/run/docker.sock:/var/run/docker.sock
  envoy:
    restart: always
    image: envoyproxy/envoy-alpine:v1.14.4
    pid: host
    volumes:
      - ${PWD}/conf/envoy.conf:/run/envoy/envoy.yaml
      - /tmp/sockets/:/run/spire/sockets/
    ports:
      - 8080:8080
    command:
      - -l
      - debug
      - --local-address-ip-version
      - v4
      - --config-path
      - /run/envoy/envoy.yaml
