---
apiVersion: v1
kind: Service
metadata:
  name: spire-federation
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.federation.service.annotations }}
    {{- toYaml .Values.federation.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.federation.service.type }}
  loadBalancerSourceRanges:
    {{- if .Values.federation.service.loadBalancerSourceRanges }}
    {{- toYaml .Values.federation.service.loadBalancerSourceRanges | nindent 4 }}
    {{- end }}
  ports:
    - name: federation
      port: {{ .Values.federation.bundle_endpoint.port }}
      targetPort: {{ .Values.federation.bundle_endpoint.port }}
      protocol: TCP
  selector:
    app: spire-server