---
apiVersion: v1
kind: Service
metadata:
  name: spire-federation
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.federation.service.annotations }}
    {{- toYaml .Values.federation.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.federation.service.type }}
  loadBalancerSourceRanges:
    {{- if .Values.federation.service.loadBalancerSourceRanges }}
    {{- toYaml .Values.federation.service.loadBalancerSourceRanges | nindent 4 }}
    {{- end }}
  ports:
    - name: federation
      port: 443
      targetPort: 443
      protocol: TCP
      {{- if .Values.federation.service.nodePort }}
      nodePort: {{ .Values.federation.service.nodePort }}
      {{- end }}
  selector:
    app: spire-server